# Generated by Django 4.1.7 on 2023-03-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecr", "0003_app_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
