# Generated by Django 4.1.7 on 2023-03-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecr", "0005_alter_app_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
