# Generated by Django 4.1.7 on 2023-03-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beekeeper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beehive",
            name="description",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
