# Generated by Django 4.1.7 on 2023-03-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beekeeper", "0002_beehive_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="beehive",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="node",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
