# Generated by Django 4.1.7 on 2023-03-22 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("beekeeper", "0003_beehive_updated_node_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="noderegistrationtoken",
            name="beehive",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="beekeeper.beehive",
            ),
        ),
    ]
