# Generated by Django 4.1.7 on 2023-03-22 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("beekeeper", "0004_noderegistrationtoken_beehive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noderegistrationtoken",
            name="beehive",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="beekeeper.beehive",
            ),
        ),
    ]
