# Generated by Django 4.1.7 on 2023-03-22 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beekeeper", "0006_alter_noderegistrationtoken_beehive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noderegistrationtoken",
            name="expires",
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
        migrations.AlterField(
            model_name="noderegistrationtoken",
            name="key",
            field=models.CharField(
                blank=True, max_length=64, primary_key=True, serialize=False
            ),
        ),
    ]
