# Generated by Django 4.1.7 on 2023-03-22 03:01

from django.db import migrations, models
import django.db.models.deletion
import waggle_cloud.beekeeper.models


class Migration(migrations.Migration):
    dependencies = [
        ("beekeeper", "0007_alter_noderegistrationtoken_expires_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="beehive",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="beekeeper.beehive",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="commissioned",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="node",
            name="retired",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="noderegistrationtoken",
            name="key",
            field=models.CharField(
                default=waggle_cloud.beekeeper.models.generate_node_registration_key,
                max_length=64,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
