# Generated by Django 4.1.7 on 2023-03-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beekeeper", "0008_node_beehive_node_commissioned_node_retired_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="notes",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="node",
            name="commissioned",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="node",
            name="retired",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
