# Generated by Django 4.1.7 on 2023-03-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beekeeper", "0009_node_notes_alter_node_commissioned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
