# Generated by Django 4.1.7 on 2023-03-22 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("beekeeper", "0012_installation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="commissioned",
        ),
        migrations.RemoveField(
            model_name="node",
            name="retired",
        ),
        migrations.AlterField(
            model_name="installation",
            name="end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="installation",
            name="is_protected",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="installation",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="node",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
